#=================================================================================

debug: true
logging:
  level:
    root: info
    com:
      cdk8s: debug
#=================================================================================

server:
  port: 9094
  servlet:
    context-path: /client-rest

#=================================================================================

spring:
  application:
    name: client-rest

#=================================================================================


tkey:
  sso:
    oauth:
      client:
        client-id: 'test_client_id_1'
        client-secret: 'test_client_secret_1'
        tkey-server-uri: 'http://sso.cdk8s.com:9091/sso'
        client-logout-redirect-uri: 'http://test1.cdk8s.com:${server.port}${server.servlet.context-path}'
        # 由前端来决定登录后的 code 回调地址
        # 当该参数设置为 true 的时候，拦截器发现未认证，会返回 JSON 提示，而不帮客户端直接重定向。
        # 用在前后端完全分离（域名完全不一致），不用 cookie 和 session 的情况下
        enable-code-callback-to-front: false
        # 如果上面的 enable-code-callback-to-front=true，则下面该回调地址不会被调用
        client-code-callback-uri: 'http://test1.cdk8s.com:${server.port}${server.servlet.context-path}/codeCallback'


#=================================================================================


